# Generated by Django 4.2.6 on 2023-11-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('category', models.TextField(max_length=255)),
                ('category_code', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('payment_mode', models.TextField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('complaint', models.TextField(max_length=255)),
            ],
        ),
    ]
